### ISSUE TITLE
MVPリリース レビュー依頼

### ISSUE THREAD

**Issue by krmkcat** [krmkcat/hitokara_navi#190]
お世話になっております。
卒業試験のMVPリリースレビュー依頼です。よろしくお願いいたします。

---

## サービス情報
- サービス名：ヒトカラナビ
- サービスURL：https://hitokara-navi.onrender.com
- 現時点でレスポンシブ対応はしておらず、スマホで見る前提で作っています

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 会員登録/ログイン
- [x] 店舗検索・一覧
  - [x] エリア・レーティング・特徴タグによるマルチ検索
- [x] 店舗詳細
  - [x] 基本情報（店舗名・住所・電話番号・公式HP・営業時間）
  - [x] 5段階レーティング
    - [x] 接触レス度（どれだけ店員さんとやりとりせずに済むか）**→名称を"接客レス度"に変更**
    - [x] 機器設定の自由度（高度な設定変更ができるか、持ち込み機材が使えるか等）
    - [x] 一人でも浮かない度（雰囲気が賑やかすぎないか、客層が団体客に偏っていないか等）**→名称を"一人利用のしやすさ"に変更**
  - [x] 特徴タグ
  - [x] レビュー抜粋とレビュー一覧へのリンク
- [x] レビュー一覧・詳細
- [x] レビュー投稿
  - [x] 項目別5段階レーティング
  - [x] 特徴タグ
  - [x] レビュー本文
- [x] マイページ
  - [x] プロフィール閲覧・編集（ニックネーム、性別、年代等）
  - [x] 投稿レビュー一覧・詳細・編集・削除
- [x] 管理者用画面
  - [x] ユーザー一覧・詳細・編集・削除
  - [x] 店舗情報一覧・詳細・登録・編集・削除

### MVPリリース時点で作らなくなった機能
- LINEアカウントで登録/ログイン（削除）
- 管理者用レビュー一覧・詳細・登録・編集・削除（削除）
- 管理者用ユーザー登録（削除）
- お問い合わせフォーム（本リリース時に）

### 追加した機能
- パスワードリセット機能
- 店名or住所によるフリーワード店舗検索
- 都道府県による店舗検索
- 管理者用タグ一覧・詳細・登録・編集・削除
- 管理者用エリア一覧・詳細・登録・編集・削除

## 本リリース時に実装したい機能
- レスポンシブ対応
- 現在地周辺の店舗検索
- 検索結果のソート機能
- お気に入り機能
- レビューに対する"役に立った"ボタン
- レビュー回数によるユーザーランク機能
- ユーザープロフィールと投稿したレビュー一覧を本人以外も見られるようにする

### トップページ
[![Image from Gyazo](https://i.gyazo.com/de60f4450edeaf6a91613cd5a5826317.png)](https://gyazo.com/de60f4450edeaf6a91613cd5a5826317)

### 店舗検索＆一覧ページ
[![Image from Gyazo](https://i.gyazo.com/4f21f8b222db3e100547bee042158fd0.png)](https://gyazo.com/4f21f8b222db3e100547bee042158fd0)
[![Image from Gyazo](https://i.gyazo.com/52db1252dbd2d12d866427f131a2be72.png)](https://gyazo.com/52db1252dbd2d12d866427f131a2be72)

### 店舗詳細ページ
[![Image from Gyazo](https://i.gyazo.com/d1e540b7ce3a990588ed1d69983a1936.png)](https://gyazo.com/d1e540b7ce3a990588ed1d69983a1936)
[![Image from Gyazo](https://i.gyazo.com/67d81da2c32dbef3216fb6fd676f9782.png)](https://gyazo.com/67d81da2c32dbef3216fb6fd676f9782)

### レビュー一覧ページ（投稿したレビュー一覧ページも概ね同様）
[![Image from Gyazo](https://i.gyazo.com/b1626861d7662492db6e1e9fec5509b3.png)](https://gyazo.com/b1626861d7662492db6e1e9fec5509b3)

### レビュー詳細ページ
[![Image from Gyazo](https://i.gyazo.com/eaa851ee70daf208943a63abdd18401f.png)](https://gyazo.com/eaa851ee70daf208943a63abdd18401f)

### レビュー編集ページ（投稿ページも概ね同様）
[![Image from Gyazo](https://i.gyazo.com/e8e7abea26c205b8b5df45665640eab2.png)](https://gyazo.com/e8e7abea26c205b8b5df45665640eab2)

### タグ編集ページ
[![Image from Gyazo](https://i.gyazo.com/51467108eeadf15f8c83cb8ead1b5d61.png)](https://gyazo.com/51467108eeadf15f8c83cb8ead1b5d61)

### マイページ
[![Image from Gyazo](https://i.gyazo.com/6a740e9b0818ce64a31173ded7a15d95.png)](https://gyazo.com/6a740e9b0818ce64a31173ded7a15d95)

### プロフィール編集ページ
[![Image from Gyazo](https://i.gyazo.com/50199615c47f5a54a78a261c3910db42.png)](https://gyazo.com/50199615c47f5a54a78a261c3910db42)

### 管理者画面：ダッシュボード
[![Image from Gyazo](https://i.gyazo.com/252dcb1c3c437d9ded599b10c8eb187f.png)](https://gyazo.com/252dcb1c3c437d9ded599b10c8eb187f)

### 管理者画面：店舗一覧（ユーザー、タグ、エリアも概ね同様）
[![Image from Gyazo](https://i.gyazo.com/e577678e446614a1fb43afde82be2feb.png)](https://gyazo.com/e577678e446614a1fb43afde82be2feb)

### 管理者画面：店舗詳細（ユーザー、タグ、エリアも概ね同様）
[![Image from Gyazo](https://i.gyazo.com/bdc2bed5b9033dee62600a2f2086b49e.png)](https://gyazo.com/bdc2bed5b9033dee62600a2f2086b49e)

### 管理者画面：店舗編集（ユーザー、タグ、エリアも概ね同様、登録も概ね同様）
[![Image from Gyazo](https://i.gyazo.com/caaa7143330ecd02435e4d915e662675.png)](https://gyazo.com/caaa7143330ecd02435e4d915e662675)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by krmkcat** [comment]
ありがとうございます！
クローズいたします。
