### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by krmkcat** [krmkcat/hitokara_navi#37]
### 概要
CSSフレームワーク導入・仮トップページ作成・初期デプロイまでは済んでいます。

### 実装予定の機能
  - [x] 会員登録・ログイン・パスワードリセット
  - [x] 店舗検索・一覧・詳細
  - [x] レビュー投稿・一覧・詳細
  - [x] マイページ
    - [x] プロフィール閲覧・編集（ニックネーム、性別、年代等）
    - [x] 投稿レビュー一覧・詳細・編集・削除
  - [x] お問い合わせフォーム
  - [x] 管理者用画面
    - [x] ユーザー一覧・詳細・登録・編集・削除
    - [x] レビュー一覧・詳細・登録・編集・削除
    - [x] 店舗情報一覧・詳細・登録・編集・削除

### 必要なページ
- [x] トップページ
- [x] 会員登録ページ
- [x] ログインページ
- [x] パスワードリセット申請ページ
- [x] パスワードリセット実行ページ
- [x] 店舗一覧
- [x] 店舗詳細
- [x] レビュー投稿
- [x] レビュー一覧
- [x] レビュー詳細
- [x] レビュー編集
- [x] マイページトップ
- [x] プロフィール編集
- [x] マイレビュー一覧
- [x] お問合せフォーム
- [x] [管理者用]ログインページ
- [x] [管理者用]ユーザー登録
- [x] [管理者用]ユーザー一覧
- [x] [管理者用]ユーザー詳細
- [x] [管理者用]ユーザー編集
- [x] [管理者用]店舗登録
- [x] [管理者用]店舗一覧
- [x] [管理者用]店舗詳細
- [x] [管理者用]店舗編集
- [x] [管理者用]レビュー登録
- [x] [管理者用]レビュー一覧
- [x] [管理者用]レビュー詳細
- [x] [管理者用]レビュー編集

**Comment by ky0613** [comment]
Projectsをクリックして、看板・issue・ストーリーポイントを確認できませんでした。
カリキュラムを参考に対応＆閲覧できる状態への対応をお願いいたします。

**Comment by krmkcat** [comment]
コメントありがとうございます。
Private設定になっておりましたので、Publicに変更いたしました。
ご確認の程よろしくお願いいたします。

**Comment by O-H-K-N** [comment]
問題ないかと思います！
LGTMです！

**Comment by krmkcat** [comment]
ありがとうございます！クローズします。
